version: "3.6"

services:
  tdd_detroid:
    image: douglasdcm/tdd-detroid
    container_name: tdd-detroid
    volumes:
      - .:/webapp
    ports:
      - 30500:5000
    working_dir: /
    depends_on:
      - postgres
    env_file: .env_docker

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - vpm-data:/var/lib/pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgresql
  # tdd-postgrest:
  #   image: douglasdcm/tdd-postgrest
  #   container_name: tdd-postgrest
  #   ports:
  #     - 30501:3000
  #   working_dir: /

volumes:
  vpm-data:
